name: AWS_CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: yarn install

	# 빌드
      - name: Build
        run: yarn build

	# 배포
      - name: S3 Deploy 
        run: aws s3 sync ./build s3://homepredictor/ --acl bucket-owner-full-control
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

	# 기존 캐시 무효화
      - name: Invalidate CloudFront Cache 
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
          PATHS: "/index.html"
        continue-on-error: true
